# Generated by Django 2.2.11 on 2023-03-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20201118_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'فرم فیلد',
                'verbose_name_plural': 'فرم فیلد ها',
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('fileds', models.ManyToManyField(to='blog.FormFields')),
            ],
            options={
                'verbose_name': 'فرم',
                'verbose_name_plural': 'فرم ها',
            },
        ),
    ]
