# Generated by Django 2.2.11 on 2023-03-02 08:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_form_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='form',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار'),
        ),
        migrations.AddField(
            model_name='form',
            name='slug',
            field=models.SlugField(default=1, max_length=100, unique=True, verbose_name='آدرس مقاله'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='form',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
