# Generated by Django 2.2.11 on 2023-03-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20230302_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='test',
            field=models.BooleanField(default=True),
        ),
    ]
